# Generated by Django 3.2 on 2023-04-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230427_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('VIP', 'VIP'), ('premium', 'Premium')], default='standard', max_length=10),
        ),
    ]
